# This pipeline will install all depedencies, lint syntax error.

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-linter:
    name: Run linter for PR
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.3.0
    - name: Checkout to specific codebase...
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install --frozen-install
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint

