# This pipeline will install all depedencies, lint syntax error.

name: Pull request linter check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-linter:
    name: Pull request linter pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Setup permission for Docker container
      run: sudo chown -R $USER:$USER ${{ github.workspace }}
    - name: Checkout to specific codebase...
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install depedencies
      run: npm install
    - name: Run lint
      run: npm run lint

